### ISSUE TITLE
BUG: freezes vim with neovim nigthly on windows

### ISSUE THREAD

**Issue by Pandademic** [VonHeikemen/fine-cmdline.nvim#21]
if you type nothing escape , vim will be frozen

**Comment by VonHeikemen** [comment]
It should be fixed now ([55bd7f0](https://github.com/VonHeikemen/fine-cmdline.nvim/commit/55bd7f0b0861782592323cbd6306eee8929327b6)).

I think is a neovim bug, I was calling `<C-x><C-z>` to stop a pending failed completion but that `<C-z>` was freezing the terminal. That should not happen, it works fine in 0.6.1 but is broken on nightly.

Anyway, I found another method so this bug should not happen anymore.

**Comment by Pandademic** [comment]
reported in the neovim repo

**Comment by VonHeikemen** [comment]
So it turns out the freezing part of the bug is because windows can't properly restore a suspended process. And **I believe** the keys `<C-x><C-z>` were being send to the window below the input, and that was causing neovim to try to suspend. This is no longer the case, the plugin doesn't try to call `<C-x><C-z>` when the input closes.

If anyone wants to make sure this doesn't happen again remap `<C-x><C-z>` to `<NOP>` in normal mode.

With vimscript.

```vim
nnoremap <C-x><C-z> <NOP>
```
Or lua.

```lua
vim.api.nvim_set_keymap('n', '<C-x><C-z>', '<NOP>', {noremap = true})
```
